import { chmodSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import YAML from "yaml";
import { type DockManifest, parseManifestFile } from "../src/core/domain/manifest.js";
import { LifecycleRunner } from "../src/core/runtime/lifecycle-runner.js";

const tempRoots: string[] = [];

afterEach(() => {
  for (const root of tempRoots.splice(0)) {
    rmSync(root, { recursive: true, force: true });
  }
});

describe("requires regression coverage", () => {
  it("parses runtime and package requirements from dock.yml", () => {
    const root = tempDir();
    writeFileSync(
      join(root, "dock.yml"),
      YAML.stringify({
        opendock: 1,
        id: "test/requires",
        requires: {
          runtimes: {
            node: ">=22.0.0 <25.0.0",
            bun: ">=1.3.0",
          },
          packages: {
            oma: {
              manager: "bun",
              name: "oh-my-agent",
              version: ">=8.43.0",
            },
          },
        },
      }),
    );

    const manifest = parseManifestFile(join(root, "dock.yml"));

    expect(manifest.requires.runtimes).toEqual({
      bun: ">=1.3.0",
      node: ">=22.0.0 <25.0.0",
    });
    expect(manifest.requires.packages.oma).toEqual({
      manager: "bun",
      name: "oh-my-agent",
      version: ">=8.43.0",
    });
  });

  it("rejects unsafe package requirement names", () => {
    const root = tempDir();
    writeFileSync(
      join(root, "dock.yml"),
      YAML.stringify({
        opendock: 1,
        id: "test/requires",
        requires: {
          packages: {
            bad: {
              manager: "bun",
              name: "oh-my-agent;rm",
              version: ">=1.0.0",
            },
          },
        },
      }),
    );

    expect(() => parseManifestFile(join(root, "dock.yml"))).toThrow(
      "package name must be a safe package identifier",
    );
  });

  it("rejects unsupported required runtimes", () => {
    const root = tempDir();
    writeFileSync(
      join(root, "dock.yml"),
      YAML.stringify({
        opendock: 1,
        id: "test/requires",
        requires: {
          runtimes: {
            ruby: ">=3.0.0",
          },
        },
      }),
    );

    expect(() => parseManifestFile(join(root, "dock.yml"))).toThrow(
      "unsupported required runtime `ruby`",
    );
  });

  it("installs missing required packages before lifecycle steps run", async () => {
    const project = tempDir();
    const bin = tempDir();
    const log = join(project, "commands.log");
    writeFakeNode(bin, log);
    writeFakeBun(bin, log);
    const manifest = omaManifest({
      install: [
        {
          id: "apply-oma",
          run: "oma -y install",
          workdir: "dock",
          platforms: {},
          export: {
            include: ["AGENTS.md"],
            exclude: [],
          },
        },
      ],
    });

    const result = await withEnv({ PATH: bin }, async () =>
      new LifecycleRunner().run(manifest, {
        projectDir: project,
        dockId: "test/oma",
        phase: "install",
        platform: "macos",
        live: false,
      }),
    );

    expect(result.reports.map((report) => `${report.id}:${report.status}`)).toEqual([
      "require-runtime-node:Ready",
      "require-runtime-bun:Ready",
      "require-package-oma:Ran",
      "apply-oma:Ran",
    ]);
    expect(result.exports.map((candidate) => candidate.path)).toEqual(["AGENTS.md"]);
    expect(readFileSync(log, "utf8")).toContain("bun:install --global oh-my-agent@latest");
    expect(
      readFileSync(join(project, ".opendock", "workdirs", "test__oma", "AGENTS.md"), "utf8"),
    ).toContain("Generated by fake OMA");
  });

  it("reruns required package installers on update even when the binary already exists", async () => {
    const project = tempDir();
    const bin = tempDir();
    const log = join(project, "commands.log");
    writeFakeNode(bin, log);
    writeFakeBun(bin, log);
    writeFakeOma(bin, log);

    const result = await withEnv({ PATH: bin }, async () =>
      new LifecycleRunner().run(omaManifest(), {
        projectDir: project,
        dockId: "test/oma",
        phase: "update",
        platform: "macos",
        live: false,
      }),
    );

    expect(result.reports.map((report) => `${report.id}:${report.status}`)).toEqual([
      "require-runtime-node:Ready",
      "require-runtime-bun:Ready",
      "require-package-oma:Ran",
    ]);
    expect(readFileSync(log, "utf8")).toContain("bun:install --global oh-my-agent@latest");
  });

  it("checks requirements during doctor without installing missing packages", () => {
    const project = tempDir();
    const bin = tempDir();
    const log = join(project, "commands.log");
    writeFakeNode(bin, log);
    writeFakeBun(bin, log);

    const result = withEnvSync({ PATH: bin }, () =>
      new LifecycleRunner().run(omaManifest(), {
        projectDir: project,
        dockId: "test/oma",
        phase: "doctor",
        platform: "macos",
        live: false,
      }),
    );

    expect(result.reports).toMatchObject([
      { id: "require-runtime-node", status: "Ready" },
      { id: "require-runtime-bun", status: "Ready" },
      { id: "require-package-oma", status: "Failed" },
    ]);
    expect(readFileSync(log, "utf8")).not.toContain("install --global");
  });
});

function omaManifest(lifecycle: Partial<DockManifest["lifecycle"]> = {}): DockManifest {
  return {
    opendock: 1,
    id: "test/oma",
    summary: "",
    requires: {
      runtimes: {
        node: ">=22.0.0 <25.0.0",
        bun: ">=1.3.0",
      },
      packages: {
        oma: {
          manager: "bun",
          name: "oh-my-agent",
          version: ">=8.43.0",
        },
      },
    },
    files: [],
    lifecycle: {
      install: lifecycle.install ?? [],
      update: lifecycle.update ?? [],
      doctor: lifecycle.doctor ?? [],
    },
  };
}

function tempDir(): string {
  const dir = mkdtempSync(join(tmpdir(), "opendock-requires-test-"));
  tempRoots.push(dir);
  return dir;
}

function writeFakeNode(bin: string, log: string): void {
  writeExecutable(
    join(bin, "node"),
    `#!/bin/sh
printf 'node:%s\\n' "$*" >> "${log}"
printf 'v22.18.0\\n'
`,
  );
}

function writeFakeBun(bin: string, log: string): void {
  writeExecutable(
    join(bin, "bun"),
    `#!/bin/sh
set -eu
printf 'bun:%s\\n' "$*" >> "${log}"
if [ "$1" = "--version" ]; then
  printf '1.3.11\\n'
  exit 0
fi
if [ "$1" = "install" ]; then
  /bin/cat > "${bin}/oma" <<'EOF'
#!/bin/sh
set -eu
printf 'oma:%s\\n' "$*" >> "${log}"
if [ "$1" = "--version" ]; then
  printf '8.43.0\\n'
  exit 0
fi
if [ "$*" = "-y install" ]; then
  printf '# Generated by fake OMA\\n' > AGENTS.md
  exit 0
fi
if [ "$*" = "-y update" ] || [ "$1" = "doctor" ]; then
  exit 0
fi
EOF
  /bin/chmod +x "${bin}/oma"
  exit 0
fi
exit 1
`,
  );
}

function writeFakeOma(bin: string, log: string): void {
  writeExecutable(
    join(bin, "oma"),
    `#!/bin/sh
set -eu
printf 'oma:%s\\n' "$*" >> "${log}"
if [ "$1" = "--version" ]; then
  printf '8.43.0\\n'
  exit 0
fi
if [ "$1" = "doctor" ]; then
  exit 0
fi
`,
  );
}

function writeExecutable(path: string, content: string): void {
  writeFileSync(path, content);
  chmodSync(path, 0o755);
}

async function withEnv<T>(env: NodeJS.ProcessEnv, fn: () => Promise<T>): Promise<T> {
  return withEnvSync(env, fn);
}

function withEnvSync<T>(env: NodeJS.ProcessEnv, fn: () => T): T {
  const previous = new Map<string, string | undefined>();
  for (const [key, value] of Object.entries(env)) {
    previous.set(key, process.env[key]);
    if (value === undefined) {
      delete process.env[key];
    } else {
      process.env[key] = value;
    }
  }
  try {
    return fn();
  } finally {
    for (const [key, value] of previous) {
      if (value === undefined) {
        delete process.env[key];
      } else {
        process.env[key] = value;
      }
    }
  }
}
